[project]
name = "llmhitbigquery-uscensus"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "altair>=5.5.0",
    "db-dtypes>=1.4.2",
    "google-cloud-bigquery>=3.31.0",
    "langchain>=0.3.23",
    "langchain-chroma>=0.2.2",
    "langchain-core>=0.3.51",
    "langchain-google-genai>=2.1.2",
    "pandas>=2.2.3",
    "regex>=2024.11.6",
    "streamlit>=1.44.1",
]
